Implementation of JIRA Features 8653 And 8654
Ginger-Automation/Ginger pull request #1680
Opened 2020-08-20 06:22 UTC by arvindgh

-Avoid creation of duplicate defect in jira based on summary and status
-Send screenshots as attachment to newly created defect in jira

2020-08-24 09:29 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                    DefectStatusColl jiraDefectStatuses = new DefectStatusColl();
Codacy found an issue: [Remove this useless assignment to local variable 'jiraDefectStatuses'.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-24 09:29 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-24 09:29 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                            string[] screenshotsPaths = screenshots[a].Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
Codacy found an issue: [Remove the array type; it is redundant.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-24 09:29 UTC, ambarkhan commented on Ginger/GingerCoreNET/Run/RunSetActions/RunSetActionAutomatedALMDefects.cs
> +                        currentALMDefectFieldsValues.Add("screenshots", String.Join(",", defectSuggestion.ScreenshotFileNames););
Codacy found an issue: [Remove this empty statement.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-24 12:01 UTC, JinendraGhodke commented
Check why Builds are failing

2020-08-25 08:13 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-25 08:13 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                    DefectStatusColl jiraDefectStatuses = new DefectStatusColl();
Codacy found an issue: [Remove this useless assignment to local variable 'jiraDefectStatuses'.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-25 08:13 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                            string[] screenshotsPaths = screenshots[a].Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
Codacy found an issue: [Remove the array type; it is redundant.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-25 08:55 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-25 08:56 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                            string[] screenshotsPaths = screenshots[a].Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
Codacy found an issue: [Remove the array type; it is redundant.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-27 03:44 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-27 03:44 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                            string[] screenshotsPaths = screenshots[a].Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
Codacy found an issue: [Remove the array type; it is redundant.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-27 07:24 UTC, JinendraGhodke commented on Ginger/GingerCore/ALM/JIRA/JiraSettings/JiraSettings.json
> +    {
did you test it for more than 1 operator ?

2020-08-27 07:33 UTC, JinendraGhodke requested changes
Handle Review comments and check why Codacy build is failing

2020-08-27 07:33 UTC, JinendraGhodke commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +
Please split this long function into smaller modules. 
CheckIfDefectExist
CreateDefect
AttachScreenshotsToDefect

2020-08-27 07:33 UTC, JinendraGhodke commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +                            if (defectStatus.Operator.ToLower().Contains("not"))
Please add Switch case and return the operator based on matching string instead of contains. We might add more operators in future

2020-08-31 04:25 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-31 04:25 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +            switch (compareOperator)
Codacy found an issue: [Add a 'default' clause to this 'switch' statement.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-31 04:28 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-31 04:28 UTC, ambarkhan commented on Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs
> +            switch (compareOperator)
Codacy found an issue: [Add a 'default' clause to this 'switch' statement.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077)

2020-08-31 04:35 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- Ginger/GingerCore/ALM/JIRA/Bll/JiraExportManager.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6043077&bid=19800324)

2020-08-31 11:58 UTC, JinendraGhodke approved these changes

2020-08-31 11:59 UTC, merged