Create certificate from .cer and .key files for Rest API
Ginger-Automation/Ginger pull request #1716
Opened 2020-10-15 14:10 UTC by arvindgh

2020-10-15 14:29 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816&bid=20608809)

2020-10-15 14:30 UTC, ambarkhan commented on Ginger/GingerCoreNET/ActionsLib/WebAPI/ActWebAPIBase.cs
> +            public static string KeyFilePath = "KeyFilePath";
Codacy found an issue: [Change the visibility of 'KeyFilePath' or make it 'const' or 'readonly'.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816)

2020-10-16 15:51 UTC, JinendraGhodke requested changes

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/Ginger/Actions/ActionEditPages/WebServices/ActWebAPIEditPage.xaml
> +                                <Actions:UCValueExpression x:Name="KeyFilePathTextBox" Margin="0,0,0,0"/>
we use x as prefix to all WFP control names e.g. xKeyFilePathTextBox

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/Ginger/Actions/ActionEditPages/WebServices/ActWebAPIEditPage.xaml
> +                                <CheckBox x:Name="DoNotImportKeyFile" Content="Import key file to Solution folder" ToolTip="If checked the selected certificate file will be imported to ~Documents\Cer
Check box name is confusing. Content says import and check box says do not import. 
Also follow naming convension

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/Ginger/packages.config
> +  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" requireReinstallation="true" />
what are these changes with requirereinstallation attribute ?

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/GingerCore/Drivers/WebServicesDriverLib/HttpWebClientUtils.cs
> +        {
What is this function used for ?

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/GingerCore/Properties/Resources.Designer.cs
> +        ///   Looks up a localized string similar to /*
Is this change relevant to this PR?

2020-10-16 15:51 UTC, JinendraGhodke commented on Ginger/GingerCore/Properties/Settings.Designer.cs
> +    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
Is it related to PR ?

2020-10-19 14:27 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816&bid=20608809)

2020-10-19 14:27 UTC, ambarkhan commented on Ginger/Ginger/Actions/ActionEditPages/WebServices/ActWebAPIEditPage.xaml.cs
> +                    //string targetPath = System.IO.Path.Combine(SolutionFolder, @"Documents\WebServices\Certificates");
Codacy found an issue: [Remove this commented out code.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816)

2020-10-19 14:27 UTC, ambarkhan commented on Ginger/GingerCoreNET/ActionsLib/WebAPI/ActWebAPIBase.cs
> +            public static string ImportKeyFile = "ImportKeyFile";
Codacy found an issue: [Change the visibility of 'ImportKeyFile' or make it 'const' or 'readonly'.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816)

2020-10-19 14:27 UTC, ambarkhan commented on Ginger/GingerCoreNET/ActionsLib/WebAPI/ActWebAPIBase.cs
> +            public static string KeyFilePath = "KeyFilePath";
Codacy found an issue: [Change the visibility of 'KeyFilePath' or make it 'const' or 'readonly'.](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6345816)

2021-03-15 05:58 UTC, closed without merging