Bug fix/official release 8792 getting error in repository for stored action that has store to variable
Ginger-Automation/Ginger pull request #1733
Opened 2020-10-23 08:17 UTC by ravirk91

Bug 8809:Exception during run activity for specific activity having Run from SR flow control
Bugfix/official release 8792 getting error in repository for stored action that has store to variable

2020-10-23 08:20 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Ginger/GingerCoreCommon/Repository/RepositoryFolder.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6389331&bid=20719037)

2020-10-23 15:31 UTC, JinendraGhodke requested changes
Check the comment for Null check added

2020-10-23 15:31 UTC, JinendraGhodke commented on Ginger/Ginger/AutomatePageLib/NewAutomatePage.xaml.cs
> +            if (mActivityPage != null)
i think we should check Why the page is null. Because in this this function we are enabling the buttons and setting visibility

2020-10-26 14:06 UTC, ambarkhan commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Ginger/GingerCoreCommon/Repository/RepositoryFolder.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ginger-Automation/Ginger/pullRequest?prid=6389331&bid=20719037)

2020-10-26 19:20 UTC, JinendraGhodke approved these changes

2020-10-26 19:41 UTC, merged