Octane enhancements- Defects attachement, Defect TS link, Caling TC
Ginger-Automation/Ginger pull request #1769
Opened 2020-11-23 13:39 UTC by Maheshkale447

2020-11-30 08:02 UTC, JinendraGhodke requested changes
Please confirm if tested from runset operation as well as manually from runset.

2020-12-07 12:50 UTC, Maheshkale447 commented on Ginger/GingerCore/ALM/OctaneCore.cs
> +                Reporter.ToLog(eLogLevel.ERROR, "Failed to import QC test set and convert it into " + GingerDicser.GetTermResValue(eTermResKey.BusinessFlow), ex);
Replaced QC with Octane

2020-12-07 12:51 UTC, Maheshkale447 commented
> Please confirm if tested from runset operation as well as manually from runset.

Checked for both, Manual as well as for runset operations

2020-12-08 08:12 UTC, JinendraGhodke approved these changes

2020-12-08 08:12 UTC, merged