BUG 8605 Fix: LiteDB Report- Missing BF Level Variables in the Report
Ginger-Automation/Ginger pull request #1873
Opened 2021-04-19 17:27 UTC by Maheshkale447

BUG 8605 Fix: LiteDB Report- Missing BF Level Variables in the Report

2021-04-27 10:34 UTC, JinendraGhodke requested changes
Few screenshot files are added which are not required. Please remove those.

2021-04-30 09:50 UTC, JinendraGhodke reviewed
Still few files like screenshot, license.txt added. Are those needed if not please remove

2021-04-30 12:54 UTC, Maheshkale447 commented
> Still few files like screenshot, license.txt added. Are those needed if not please remove

at-least one SS need to be in folder in order to SS folder to get created. License.txt is needed.
Checked all other files. all are needed.

2021-04-30 13:24 UTC, JinendraGhodke approved these changes

2021-04-30 13:25 UTC, JinendraGhodke approved these changes

2021-04-30 14:01 UTC, merged