Fixed issue when running webserver action
Ginger-Automation/Ginger pull request #2082
Opened 2021-09-23 04:00 UTC by ranjit5544

2021-09-23 09:24 UTC, Maheshkale447 approved these changes

2021-09-23 11:40 UTC, JinendraGhodke requested changes
it was working for user on old Ginger and started failing on 3.9. So we need to understand what is the reason.

2021-09-23 13:39 UTC, ranjit5544 commented
> it was working for user on old Ginger and started failing on 3.9. So we need to understand what is the reason.

After code is moved to GingerCoreNet this issue occurred. The instance was not getting create. Now, we are creating the instance.

2021-09-27 11:08 UTC, closed without merging

2021-09-27 11:09 UTC, Maheshkale447 commented
Another PR is opened for this changes