Bug_9397_Result Image On Close eye
Ginger-Automation/Ginger pull request #2230
Opened 2022-01-07 10:18 UTC by prashelke

Result Image On Close Eye

2022-01-07 11:58 UTC, Maheshkale447 requested changes

2022-01-07 11:58 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/ActionsLib/UI/VisualTesting/ActVisualTesting.cs
> +            [EnumValueDescription("OCR Analyzer - Not Implemented")]
Please comment the code again

2022-01-07 13:14 UTC, prashelke commented on Ginger/GingerCoreNET/ActionsLib/UI/VisualTesting/ActVisualTesting.cs
> +            [EnumValueDescription("OCR Analyzer - Not Implemented")]
Done

2022-01-10 10:25 UTC, Maheshkale447 approved these changes

2022-01-24 13:44 UTC, merged