Activity as Link from shared repository
Ginger-Automation/Ginger pull request #2335
Opened 2022-03-08 09:28 UTC by Maheshkale447

2022-03-09 11:02 UTC, JinendraGhodke requested changes

2022-03-10 15:38 UTC, Maheshkale447 commented on Ginger/GingerCoreNETUnitTest/SolutionTestsLib/RepositorySerializerTest.cs
> +            Assert.IsTrue(xml.Length < 850, "Verify minimal xml is less than 850 bytes");
Yes, type is added to XML, hence unit test case was failing, so had to change the length size

2022-03-10 15:44 UTC, Maheshkale447 commented on Ginger/GingerCoreCommon/Repository/RepositoryItemBase.cs
> +    public enum eType
done

2022-03-10 15:45 UTC, Maheshkale447 commented on Ginger/GingerCoreCommon/Repository/NewRepositorySerializer.cs
> +                    {
Yes, so actions won't be added in XML

2022-03-10 15:51 UTC, Maheshkale447 commented on Ginger/GingerCoreCommon/WorkSpaceLib/GingerCoreCommonWorkSpace.cs
> +
No, Solution repository object is not available on solution.cs,

2022-03-10 15:52 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/WorkSpaceLib/WorkSpace.cs
> +                GingerCoreCommonWorkSpace.Instance.SolutionRepository = this.SolutionRepository;
yes, added that line temporarily, removed now

2022-03-21 10:03 UTC, merged