Insert implementation and bug fixes
Ginger-Automation/Ginger pull request #2376
Opened 2022-04-07 08:18 UTC by rajdeep-mukh

2022-04-08 10:22 UTC, JinendraGhodke requested changes

2022-04-08 10:22 UTC, JinendraGhodke commented on Ginger/Ginger/Actions/ActionEditPages/ValidationDBPage.xaml.cs
> +                if (ValidationCfgComboBox.Items.Cast<ComboEnumItem>().Where(m => m.text.ToString().Equals("Insert")) == null
use enum to compare the combo item eDBValidationType.Insert instead of hard coded string

2022-04-08 10:22 UTC, JinendraGhodke commented on Ginger/Ginger/Actions/ActionEditPages/ValidationDBPage.xaml.cs
> +                            CosmosParametersGrid.Visibility = Visibility.Visible;
rename the Grid as UpdateDBParamGrid
Currently it is used only for Cosmos but in future it might be reused for other DB Types

2022-04-08 10:22 UTC, JinendraGhodke commented on Ginger/GingerCoreNET/Database/NoSqlBase/GingerCosmos.cs
> +                        if (!SQLCalculated.Contains("where"))
what if user will execute a select query without where clause ? code will go to else part

2022-04-11 07:36 UTC, Maheshkale447 approved these changes

2022-04-12 06:45 UTC, merged