updated user messages & UI with correct spelling
Ginger-Automation/Ginger pull request #2526
Opened 2022-07-05 12:52 UTC by amitamir

2022-07-05 12:53 UTC, amitamir commented
not sure if branch is updated with latest commits from Releases/Official-Release

2022-07-06 05:02 UTC, Maheshkale447 requested changes

2022-07-06 05:02 UTC, Maheshkale447 commented on Ginger/GingerCoreTest/UITests/PBDriverWidgetTest.cs
> +            c.LocateValueCalculated = "CSM Widgets Test Application";
Please check if modified unit test cases are working fine

2022-07-06 05:02 UTC, Maheshkale447 commented on Ginger/Ginger/ApplicationModelsLib/ModelOptionalValue/AddModelOptionalValuesWizard.cs
> +            [EnumValueDescription("JSON")]
Please check if solution from previous version is loading with old enum value

2022-07-06 05:02 UTC, Maheshkale447 commented on Ginger/Ginger/ApplicationModelsLib/APIModels/APIModelWizard/AddAPIModelWizard.cs
> +            [EnumValueDescription("JSON Templates")]
Please check if solution from previous version is loading with old enum value

2022-07-07 17:17 UTC, Maheshkale447 approved these changes

2022-07-07 17:17 UTC, merged