D16148_Visual Testing issue resolved
Ginger-Automation/Ginger pull request #2629
Opened 2022-08-25 09:23 UTC by prashelke

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is point to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for Existing Functionality
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments

2022-08-25 09:48 UTC, Maheshkale447 requested changes

2022-08-25 09:48 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/ActionsLib/UI/VisualTesting/ApplitoolsAnalyzer.cs
> +                if (WorkSpace.Instance.RunsetExecutor.RunSetConfig != null && WorkSpace.Instance.RunsetExecutor.RunSetConfig.GingerRunners.Any() && WorkSpace.Instance.RunsetExecutor.RunSetConfig.Ging
remove unwanted any()

2022-08-25 09:51 UTC, prashelke commented on Ginger/GingerCoreNET/ActionsLib/UI/VisualTesting/ApplitoolsAnalyzer.cs
> +                if (WorkSpace.Instance.RunsetExecutor.RunSetConfig != null && WorkSpace.Instance.RunsetExecutor.RunSetConfig.GingerRunners.Any() && WorkSpace.Instance.RunsetExecutor.RunSetConfig.Ging
Done

2022-08-25 16:28 UTC, Maheshkale447 approved these changes

2022-08-26 09:32 UTC, Maheshkale447 approved these changes

2022-08-26 09:32 UTC, merged