Fixed some Defects from Octane:
Ginger-Automation/Ginger pull request #2795
Opened 2022-12-05 11:26 UTC by amitamir

1. D18052 - After adding model global parameter getting unexpected error under BF tab

2. D17052 - External integrations changes isn't showing into modified solution item.

3. D16001 - Getting Star sign (Astrik mark) for Business Flows when we are coming back from Automate tab without making any changes

also fixed an issue on UCRadioButtons, the radio button is checked property was binded to an enum value, and its update trigger was OnPropertyChanged which I have added in previous commits. removed the redundant binding between the Radio button is checked property to the enum value.

also in order to fix D16001, turned dirty tracking off while we are loading the action edit page which would've mark the Action->Activtiy->BF->Runset as dirty.

fixed an issue where deleting all Model Global Parameters/Remote Services Grid would not set the CurrentSelectedItem to null and kept reference to the removed object.

with that said, it is requiring further testing on what happens when we remove all BF/Agents/any tree items

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is point to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for Existing Functionality
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments

2022-12-05 12:02 UTC, amitamir commented
regarding this comment:
"with that said, it is requiring further testing on what happens when we remove all BF/Agents/any tree items"

I have tested it across the solution, no issues were found on more places

2022-12-05 12:12 UTC, Maheshkale447 requested changes

2022-12-06 10:28 UTC, Maheshkale447 approved these changes

2022-12-06 10:29 UTC, amitamir commented on Ginger/Ginger/UserControlsLib/UCRadioButtons.xaml.cs
> -                    ObjFieldBinding(button, RadioButton.IsCheckedProperty, obj, property);
this function was copied from a different UC we had, we are binding the IsCheckedProperty which is a boolean to the Enum property which is usually represented as a string and holding a different value than true/false, so the radio button does not know to set its is checked property the right way

2022-12-06 11:05 UTC, merged