Feature/rqm update changes
Ginger-Automation/Ginger pull request #2878
Opened 2023-02-09 09:06 UTC by prashelke

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is point to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for Existing Functionality
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments

2023-02-09 09:08 UTC, prashelke commented
Unit test is added in Rqm Repository we are not able to added unit test in ginger because we only used Rqm Repository dll in ginger so need to add into Regression suite

2023-02-10 07:58 UTC, Maheshkale447 requested changes

2023-02-10 07:58 UTC, Maheshkale447 commented on Ginger/Ginger/App.config
> -<?xml version="1.0" encoding="utf-8"?>
App.config not needed anymore?

2023-02-10 09:35 UTC, prashelke commented on Ginger/Ginger/App.config
> -<?xml version="1.0" encoding="utf-8"?>
we need it I have updated it

2023-02-10 10:20 UTC, prashelke commented on Ginger/Ginger/App.config
> -<?xml version="1.0" encoding="utf-8"?>
we need it

2023-02-13 06:26 UTC, merged