Java Driver fixes
Ginger-Automation/Ginger pull request #2961
Opened 2023-04-26 17:18 UTC by ravirk91

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Help Libray document is updated accordingly for Feature changes.

2023-04-28 12:40 UTC, Maheshkale447 requested changes

2023-04-28 12:40 UTC, Maheshkale447 commented on Ginger/GingerCore/Actions/ActLaunchJavaWSApplication.cs
> +                ArrayList processNames = new();
Please declare local variable for processNames List

2023-04-29 10:48 UTC, Maheshkale447 submitted a review, later dismissed

2023-05-05 18:43 UTC, JinendraGhodke requested changes

2023-05-05 18:43 UTC, JinendraGhodke commented on Ginger/GingerCoreNET/Run/GingerExecutionEngine.cs
> +                CurrentBusinessFlow.CurrentActivity.Status = eRunStatus.Stopped;
we discussed to remove this part and handle it as part of driver load waiting time right ?

2023-05-05 18:43 UTC, JinendraGhodke commented on Ginger/GingerCore/Drivers/JavaDriverLib/GingerJavaAgent/agent/com/amdocs/ginger/SwingHelper.java
> +    		else if(Wtitle.contains(actualTitle))
i would like to understand more details about this change

2023-05-15 11:54 UTC, Maheshkale447 approved these changes

2023-05-15 12:08 UTC, merged