Feature/excel header identity
Ginger-Automation/Ginger pull request #3080
Opened 2023-06-26 04:51 UTC by manas-droid

1. Added a new Input Control to accept Table Header Row Number
2. Added precise error messages

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Help Libray document is updated accordingly for Feature changes.

2023-07-17 08:05 UTC, Maheshkale447 requested changes

2023-07-21 16:43 UTC, manas-droid commented on Ginger/GingerCoreNET/ActionsLib/ActExcel.cs
> +                    Error = ex.Message + " " + $"at Row Number {HeaderRowNum}";
Implemented the requested changes

2023-07-24 10:58 UTC, manas-droid commented on Ginger/GingerCoreNET/Run/Excels/ExcelNPOIOperations.cs
> +                Reporter.ToLog(eLogLevel.WARN, exceptionMessage);
The requested change was implemented in the latest code

2023-07-24 10:58 UTC, manas-droid commented on Ginger/GingerCoreNET/Run/Excels/ExcelNPOIOperations.cs
> +                    throw new ArgumentException("File DOES NOT Exist or is currently being used by some other application, Please verify if the File Path is valid");
The requested change was implemented in the latest code

2023-07-24 10:58 UTC, manas-droid commented on Ginger/GingerCoreNET/Run/Excels/ExcelNPOIOperations.cs
> +                Regex regex = new Regex(@"(^[A-Z]+\d+$)|(^[A-Z]+\d+:[A-Z]+\d+$)");
The requested change was implemented in the latest code

2023-07-27 08:07 UTC, Maheshkale447 approved these changes

2023-07-27 08:08 UTC, merged