Database Action Bug Fix
Ginger-Automation/Ginger pull request #3111
Opened 2023-07-12 13:21 UTC by AmanPrasad43

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Help Libray document is updated accordingly for Feature changes.

2023-07-13 07:09 UTC, Maheshkale447 requested changes

2023-07-13 07:09 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/Database/DatabaseOperations.cs
>                      if (Database.DBType == Database.eDBTypes.Cassandra)
Replace If with Switch

2023-07-13 07:09 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/Database/DatabaseOperations.cs
>                              {
Remove oracle case from switch as it is handled above
Also check if switch case is needed here as its being evealuated for each row in table.rows.

2023-07-13 07:09 UTC, Maheshkale447 commented on Ginger/GingerCoreNET/Database/DatabaseOperations.cs
> +        public string GetConnectedUsername()
Add comments that its being used for Oracle only

2023-07-14 12:16 UTC, AmanPrasad43 commented
Got some conflict

2023-07-14 12:16 UTC, closed without merging