License Updated in Newly Added Files
Ginger-Automation/Ginger pull request #3272
Opened 2023-10-05 14:00 UTC by prashelke

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Help Libray document is updated accordingly for Feature changes.

2023-10-06 15:26 UTC, Maheshkale447 requested changes

2023-10-06 15:26 UTC, Maheshkale447 commented on Ginger/Ginger/Activities/ActivitiesListViewHelper.cs
> +            publishGroup.Header = string.Concat("Publish/Unpublished ", GingerDicser.GetTermResValue(eTermResKey.ActivitiesGroup));
Keep it as Unpublish

2023-10-09 04:55 UTC, prashelke commented on Ginger/Ginger/Activities/ActivitiesListViewHelper.cs
> +            publishGroup.Header = string.Concat("Publish/Unpublished ", GingerDicser.GetTermResValue(eTermResKey.ActivitiesGroup));
done

2023-10-09 06:23 UTC, Maheshkale447 approved these changes

2023-10-09 06:23 UTC, merged