Performance Changes for Weak Event Pattern
Ginger-Automation/Ginger pull request #3351
Opened 2023-12-01 12:02 UTC by prashelke

Thank you for your contribution.
Before submitting this PR, please make sure:
- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Help Libray document is updated accordingly for Feature changes.

2023-12-12 11:00 UTC, Maheshkale447 requested changes

2023-12-12 11:00 UTC, Maheshkale447 commented on Ginger/Ginger/UserControlsLib/UCComboBox.xaml.cs
> +using System.ComponentModel;
Remove unwanted usings

2023-12-12 11:12 UTC, prashelke commented on Ginger/Ginger/Actions/UserControls/UCActionDetails.xaml.cs
> +            this.DataContextChanged += UserControl_DataContextChanged;
not able to apply weak event pattern here

2023-12-12 11:28 UTC, prashelke commented on Ginger/Ginger/ApplicationModelsLib/POMModels/PomElementsPage.xaml.cs
> +                xMainElementsGrid.PasteItemEvent += PasteElementEvent;
Not able to added Weak Event Pattern

2023-12-12 11:29 UTC, prashelke commented on Ginger/Ginger/ApplicationModelsLib/ModelParams Pages/ModelExpectedValueParamSelectionPage.xaml.cs
>              selectBtn.Click += new RoutedEventHandler(selectBtn_Click);
added

2023-12-12 11:30 UTC, prashelke commented on Ginger/Ginger/AutomatePageLib/NewAutomatePage.xaml.cs
> +                PropertyChangedEventManager.AddHandler(source: mActivity, handler: Activity_PropertyChanged, propertyName: allProperties);
Done

2023-12-12 12:20 UTC, prashelke commented on Ginger/Ginger/UserControlsLib/UCComboBox.xaml.cs
> +using System.ComponentModel;
Done

2023-12-12 12:20 UTC, prashelke commented on Ginger/Ginger/RunSetPageLib/NewRunSetPage.xaml.cs
>              xDefaultTestStageRadioBtn.Checked += XDefaultTestStageRadioBtn_Checked;
Added

2023-12-12 12:20 UTC, prashelke commented on Ginger/Ginger/RunSetPageLib/NewRunSetPage.xaml.cs
> -            if (!_ignoreValidationRules)
done

2023-12-12 12:20 UTC, prashelke commented on Ginger/Ginger/AutomatePageLib/BusinessFlowsAutomatePage.xaml.cs
> +using System.ComponentModel;
done

2023-12-12 12:24 UTC, prashelke commented on Ginger/Ginger/Activities/ActivityPage.xaml.cs
> +                        WeakEventManager<ActionsListViewPage, RoutedEventArgs>.AddHandler(source: mActionsPage, eventName: nameof(ActionsListViewPage.ShiftToActionEditEvent), handler: MActionsPage_Sh
done

2023-12-12 12:24 UTC, prashelke commented on Ginger/Ginger/Actions/UserControls/UCValueExpression.xaml.cs
> +using System.Windows.Controls.Primitives;
done

2023-12-12 12:25 UTC, prashelke commented on Ginger/Ginger/Actions/ActionConversion/SelectActionWzardPage.xaml.cs
> +using System.Windows;
done

2023-12-13 08:46 UTC, Maheshkale447 approved these changes

2023-12-13 09:12 UTC, merged