D40129_D40130_D40131_CLI Orchestration Fix
Ginger-Automation/Ginger pull request #3651
Opened 2024-04-30 11:52 UTC by prashelke

Thank you for your contribution.
Before submitting this PR, please make sure:

- [ ] PR description and commit message should describe the changes done in this PR
- [ ] Verify the PR is pointing to correct branch i.e. Release or Beta branch if the code fix is for specific release , else point it to master
- [ ] Latest Code from master or specific release branch is merged to your branch
- [ ] No unwanted\commented\junk code is included
- [ ] No new warning upon build solution
- [ ] Code Summary\Comments are added to my code which explains what my code is doing
- [ ] Existing unit test cases are passed
- [ ] New Unit tests are added for your development
- [ ] Sanity Tests are successfully executed for New and Existing Functionality
- [ ] Verify that changes are compatible with all relevant browsers and platforms.
- [ ] After creating pull request there should not be any conflicts
- [ ] Resolve all Codacy comments
- [ ] Builds and checks are passed before PR is sent for review
- [ ] Resolve code review comments
- [ ] Update the Help Library document to match any feature changes

2024-04-30 13:16 UTC, Maheshkale447 requested changes

2024-04-30 13:16 UTC, Maheshkale447 commented on Ginger/Ginger/Actions/ActionEditPages/ActCLIOrchestrationEditPage.xaml
> +            <usercontrols:ImageMakerControl Grid.Column="3" x:Name="FilePathNote" ToolTip="Note - supported file .Vbs,.js,.sh,.exe." SetAsFontImageWithSize="12" ImageType="Info" Width="12" Height="12
add *.bat

2024-04-30 13:27 UTC, prashelke commented on Ginger/Ginger/Actions/ActionEditPages/ActCLIOrchestrationEditPage.xaml
> +            <usercontrols:ImageMakerControl Grid.Column="3" x:Name="FilePathNote" ToolTip="Note - supported file .Vbs,.js,.sh,.exe." SetAsFontImageWithSize="12" ImageType="Info" Width="12" Height="12
done

2024-05-02 02:29 UTC, Maheshkale447 approved these changes

2024-05-02 06:34 UTC, merged